{
	"version": 1478395802,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background-sheet0.png",
		"images/chicken-sheet0.png",
		"images/bullet-sheet0.png",
		"images/bullet-sheet1.png",
		"images/flowground-sheet0.png",
		"images/explode-sheet0.png",
		"images/monster-sheet0.png",
		"images/bullet2-sheet0.png",
		"images/ebullet-sheet0.png",
		"images/bleed-sheet0.png",
		"images/bigbullet2-sheet0.png",
		"images/heart-sheet0.png",
		"images/start-sheet0.png",
		"images/pink-sheet0.png",
		"images/pink-sheet1.png",
		"images/flyheart.png",
		"images/z-sheet0.png",
		"images/z-sheet1.png",
		"images/sprite-sheet0.png",
		"images/successfully-sheet0.png",
		"images/happy-sheet0.png",
		"images/control-sheet0.png",
		"media/butter 2.m4a",
		"media/butter 2.ogg",
		"media/falcom sound team jdk - 束の间の休息.m4a",
		"media/falcom sound team jdk - 束の间の休息.ogg",
		"media/小鸡叫.m4a",
		"media/小鸡叫.ogg",
		"media/falcom sound team jdk - 撃破!!.m4a",
		"media/falcom sound team jdk - 撃破!!.ogg",
		"media/falcom sound team jdk - 撃破!!_clip.m4a",
		"media/falcom sound team jdk - 撃破!!_clip.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}