{
	"version": 1488625630,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background-sheet0.png",
		"images/chicken-sheet0.png",
		"images/bullet-sheet0.png",
		"images/bullet-sheet1.png",
		"images/flowground-sheet0.png",
		"images/explode-sheet0.png",
		"images/monster-sheet0.png",
		"images/bullet2-sheet0.png",
		"images/ebullet-sheet0.png",
		"images/bleed-sheet0.png",
		"images/bigbullet2-sheet0.png",
		"images/heart-sheet0.png",
		"images/start-sheet0.png",
		"images/pink-sheet0.png",
		"images/pink-sheet1.png",
		"images/flyheart.png",
		"images/z-sheet0.png",
		"images/z-sheet1.png",
		"images/sprite-sheet0.png",
		"images/successfully-sheet0.png",
		"images/happy-sheet0.png",
		"images/control-sheet0.png",
		"images/direction_down-sheet0.png",
		"images/direction_left-sheet0.png",
		"images/direction_right-sheet0.png",
		"images/direction_up-sheet0.png",
		"media/butter 2.m4a",
		"media/butter 2.ogg",
		"media/endsound.m4a",
		"media/endsound.ogg",
		"media/startsound.m4a",
		"media/startsound.ogg",
		"media/chickyep2.m4a",
		"media/chickyep2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}